const Styles = {
    Boilerplate: {
        padding: "0px",
        margin: "0px",
        color: "#000",
        fontStyle: "normal",
        fontWeight: "normal",
        // RN - fontSize: "100%",
        listStyleType: "none",
        textDecoration: "none",
        // RN - border: "none",
        verticalAlign: "baseline",
        textAlign: "left",
        lineHeight: "120%",
        fontFamily: "Indie Flower",
    },
    Body: {
        backgroundColor: "#fffff6",
        // RN - fontSize: 16,
        paddingLeft: "2%",
        paddingRight: "2%",
    },
    H1: {
        fontSize: 40,
        marginTop: 20,
        marginBottom: 5,
    },
    Container: {
        backgroundColor: "#ffffef",
        // RN - border: "1px solid lightgray",
        padding: 10,
        borderRadius: 5,
        marginTop: 5,
        marginBottom: 5,
    },
    Arrow: {
        color: "gray",
        // RN - userSelect: "none",
        // RN - fontsize: 12,
    },
    Input: {
        // RN - border: "1px solid lightgray",
        // RN - fontSize: 18,
        // RN - can not be applied to Picker - fontSize: 18,
        marginBottom: 5,
        padding: 2,
        // RN - not allowed on Picker - lineHeight: null,
        // RN - not allowed - resize: "vertical",
        borderRadius: 5,
    },
    InputText: {
        height: 26,
        padding: 2,
    },
    InputMaxSize: {
        width: "98%",
    },
    InputVariableSize1: {
        width: "90%",
    },
    InputVariableSize2: {
        width: "90%",
    },
    LabelContainer: {
        marginTop: 10,
    },
    Label: {
        // RN - font not defined - fontFamily: "Courier New",
        // RN - not allowed? - fontWeight: "bold",
    },
    LabelTitle: {
        marginBottom: 3,
    },
    TextWithInputFont: {
        marginTop: 2,
        fontFamily: "Indie Flower",
        lineHeight: "160%",
    },
    CheckboxLabel: {
        height: 26,
        // RN - not allowed - display: "inline",
        paddingLeft: 5,
    },
    Button: {
        backgroundColor: "#ffffdf",
        padding: 7,
        marginBottom: 5,
        marginRight: 5,
        minWidth: 24,
        minHeight: 30,
        borderRadius: 5,
        textAlign: "center",
        // RN - border: "1px solid lightgray",
        cursor: "pointer",
        fontSize: 14,
        outline: "none",
    },
    ButtonHovered: {
        backgroundColor: "#ffffcf",
        padding: 7,
        marginBottom: 5,
        marginRight: 5,
        minWidth: 24,
        minHeight: 30,
        borderRadius: 5,
        textAlign: "center",
        // RN - border: "1px solid lightgray",
        cursor: "pointer",
        fontSize: 14,
        outline: "none",
    },
    ButtonClicked: {
        backgroundColor: "#ffffaf",
        padding: 7,
        marginBottom: 5,
        marginRight: 5,
        minWidth: 24,
        minHeight: 30,
        borderRadius: 5,
        textAlign: "center",
        // RN - border: "1px solid lightgray",
        cursor: "pointer",
        fontSize: 14,
        outline: "none",
    },
    ButtonContainer: {
        marginLeft: 5,
    },
    Link: {
        textDecoration: "none",
        color: "#cc9900",
        cursor: "pointer",
        // RN - not allowed - userSelect: "none",
        outline: "none",
    },
    LinkHovered: {
        textDecoration: "none",
        color: "#cc8100",
        cursor: "pointer",
        // RN - not allowed - userSelect: "none",
        outline: "none",
    },
    LinkClicked: {
        textDecoration: "none",
        color: "#cc4600",
        cursor: "pointer",
        // RN - not allowed - userSelect: "none",
        outline: "none",
    },
    Spacer: {
        height: 50,
    },
}

export default Styles